### ISSUE TITLE
Build successfully but run faild

### ISSUE THREAD

**Issue by Superlee506** [nackdai/aten#3]
Hi, Thanks for this great project, I follow your build steps, and build successfuly on Win10,
But when I run the svgftest project, it failed.
My build system is as below:
Win 10 (professional)
cuda 10.1 (cuda_10.1.243_426.00_win10)
cmake 1.17
Any suggestion would be appreciated!!

```
GL Version(4.6.0 NVIDIA 426.00)?nAsset is not registered [sp_luk] (Texture)
Asset is not registered [sp_luk-nml] (Texture)
Asset is not registered [00_skap] (Texture)
Asset is not registered [01_STUB] (Texture)
Asset is not registered [01_STUB-nml] (Texture)
Asset is not registered [01_S_ba] (Texture)
Asset is not registered [01_St_kp] (Texture)
Asset is not registered [01_St_kp-nml] (Texture)
Asset is not registered [x01_st] (Texture)
Asset is not registered [KAMEN-stup] (Texture)
Asset is not registered [reljef] (Texture)
Asset is not registered [reljef-nml] (Texture)
Asset is not registered [KAMEN] (Texture)
Asset is not registered [KAMEN-nml] (Texture)
Asset is not registered [prozor1] (Texture)
Asset is not registered [vrata_kr] (Texture)
Asset is not registered [vrata_ko] (Texture)
Asset is not registered [sponza] (Object)
(../../asset/sponza/sponza.obj)
    61390[vertices]
    66450[polygons]
Asset is not registered [sponza_lod] (Object)
(../../asset/sponza/sponza_lod.obj)
    70750[vertices]
    12852[polygons]
Asset is not registered [studio015] (Texture)
CUDA error at E:/Document/VSProject/aten-master/src/libidaten/kernel/GenMipMaps.cu:124 code=98(invalid device function) "cudaGetLastError()"
assert : E:\Document\VSProject\aten-master\src\libidaten\cuda\cudautil.h(43)
```

**Comment by nackdai** [comment]
Which project did you get failures?

**Comment by nackdai** [comment]
Sorry for your inconvenience, I will investigate.

**Comment by nackdai** [comment]
I fixed. I believe it might be fine. Could you try again?

**Comment by Superlee506** [comment]
@nackdai Thanks for your reply. I will try again on windows. Thanks again for this great project!
Addtionnaly, I also run succussfully on the ubuntu 16.04.
But the warnings  "Asset is nor registered" always come up, what does this warning means?

**Comment by nackdai** [comment]
In an application, register asset data for caching. And, for first registering, there is no registered assets. Therefore, the warning happens. I have noticed I should fix it...
Sorry for your confusing.

**Comment by Superlee506** [comment]
@nackdai Copy that, Thanks!

Your implement of 'SVGF' run fater than the original paper's, that's amazing!
