### ISSUE TITLE
When I test the "ObjCornellBoxScene, 1024spp-100bounces"  with "idatentest", the result is still noisy.

### ISSUE THREAD

**Issue by Superlee506** [nackdai/aten#4]
Hi, nackdai,
Thanks for your help, I can run this project successfully, and I want to render some gound truth image with more ssp and bounces.
So I test on the ObjCornellBoxScene with 1024 spp and 100 bounce, however the result image is still
noisy. I don't know why. I'm confused with this. can you check it?
Additionaly I test it on ubuntu, and the sample method is "IDATEN_SAMPLER_CMJ".
Sorry for bother you again.

**Comment by Superlee506** [comment]
Additionally, when I test the svgftest project and choose the "PT Model" with 4096  ssp，the result image is also noisy.  @nackdai

**Comment by nackdai** [comment]
To be honest, for svgftest, I have never confirmed result with other spp cases except 1spp.
For idatentest, it seems that it is bug, I will investigate. But, if you render image, you can do with checking `progressive`, which is in GUI window, with 1spp.

**Comment by Superlee506** [comment]
@nackdai Thanks nackdai, I will try it. 
Thanks for fixing the bugs.

**Comment by Superlee506** [comment]
@nackdai It works!!! Thanks nackdai.
When I become familiar with your project, I wish I could contribute to it.
I aslo find another bug, this project just works fine with "ObjCornellBoxScene"  and "SponzaScene", and it fails with other scence.
But this bug doesn't affect my research, I just need one scene for testing~
Thank again, you really help me a lot. 
`Segmentation fault (core dumped)`

**Comment by nackdai** [comment]
To be honest, I confirmed my program (for GPU) with `ObjCornellBoxScene` and `SponzaScene`, therefore, I can't guarantee to run the application with other scenes.

I have understood to write document or wiki...
