### ISSUE TITLE
nvidia-docker2 is deprecated, use NVIDIA Container Toolkit

### ISSUE THREAD

**Issue by blockspacer** [nackdai/aten#5]
see https://www.pugetsystems.com/labs/hpc/Workstation-Setup-for-Docker-with-the-New-NVIDIA-Container-Toolkit-nvidia-docker2-is-deprecated-1568/

also `/usr/local/clang_8.0.0` not installed in container, like so https://github.com/copperbits/TON/commit/dc7f58cbc8cf5a8f34f18f7c14eda1a099ec2425#diff-d5ca1f79e370c2cc70dd64bec3600d50R5 (replace with 18.04 version)

also please add in `README.md` `git submodule update --init --recursive`

**Comment by nackdai** [comment]
I also know I should use NVIDIA Container Toolkit. But, it seems that docker-composer don't support it yet. Therefore, I don't use it.

And, I will update README

**Comment by nackdai** [comment]
I updated Dockerfile and README

**Comment by blockspacer** [comment]
@nackdai 
Thanks
