### ISSUE TITLE
RunCMake.sh arguments

### ISSUE THREAD

**Issue by blockspacer** [nackdai/aten#6]
RunCMake.sh requires some arguments, please add example in readme

```bash
compute_capability=${2}
```

compute_capability is required argument or you will get `nvcc fatal : Unsupported gpu architecture 'compute_`

```bash
./RunCMake.sh Release 61
```

where 61 from

```bash
/path/to/cuda/extras/demo_suite/deviceQuery | grep 'CUDA Capability'  
# CUDA Capability Major/Minor version number:    6.1
```

**Comment by nackdai** [comment]
I have already written about `RunCMake.sh`, but it seems that it is little difficult to notice it. I will update later.

**Comment by nackdai** [comment]
I updated README

**Comment by blockspacer** [comment]
@nackdai Thanks
