### ISSUE TITLE
libomp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by blockspacer** [nackdai/aten#7]
using docker-compose from README.md

```bash
./aorenderer/aorenderer 

./aorenderer/aorenderer: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory
```

fixable by

```bash
apt update
apt-get install -y libomp5 libomp-dev freeglut3 freeglut3-dev libxi-dev libxmu-dev mesa-utils libgl1-mesa-glx pkg-config \
        libxau-dev \
        libxdmcp-dev \
        libxcb1-dev \
        libxext-dev \
        libx11-dev
```

**Comment by nackdai** [comment]
Did you get this error in Docker container? If so, I've never seen this error.

**Comment by blockspacer** [comment]
> Did you get this error in Docker container? If so, I've never seen this error.
> And, I will update Ubuntu version in Dockerfile.

yes, i got that error with `NVIDIA Container Toolkit`

**Comment by nackdai** [comment]
I see. To be honest, I have not used `NVIDIA Container Toolkit` yet.

**Comment by nackdai** [comment]
I confirmed below environment:

* Ubuntu 18.04
* docker 19.03.5
* docker-compose 1.25.0-rc2
* nvidia driver 430.50
* cuda 10.1

But, unfortunately I can't reproduce what you reported.
Could you tell me commands which you did?

For exmaple,
```shell
$ docker-compose run aten
$ cd aten
$ mkdir build
...
```

**Comment by blockspacer** [comment]
> * nvidia driver

Maybe i used wrong nvidia driver version. I managed to build code using host OS, without docker.
