### ISSUE TITLE
nvidia-docker libGL error: failed to load driver: "swrast"

### ISSUE THREAD

**Issue by blockspacer** [nackdai/aten#8]
using docker-compose

related to https://github.com/NVIDIA/nvidia-docker/issues/534#issuecomment-515695404

fixable by https://github.com/Seanmatthews/ros-docker-gazebo/blob/master/kinetic/Dockerfile#L8

**Comment by nackdai** [comment]
Did you get this error in Docker container?

**Comment by blockspacer** [comment]
> Did you get this error in Docker container?

yes, i got that error with `NVIDIA Container Toolkit`

**Comment by nackdai** [comment]
I see. To be honest, I have not used `NVIDIA Container Toolkit` yet.

**Comment by nackdai** [comment]
I confirmed below environment:

* Ubuntu 18.04
* docker 19.03.5
* docker-compose 1.25.0-rc2
* nvidia driver 430.50
* cuda 10.1

But, unfortunately I can't reproduce what you reported.
Could you tell me commands which you did?

For exmaple,
```shell
$ docker-compose run aten
$ cd aten
$ mkdir build
...
```

**Comment by blockspacer** [comment]
> * nvidia driver

Maybe i used wrong nvidia driver version. I managed to build code using host OS, without docker.
